version: "3.8"
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    container_name: "reddit"
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=rocklee
      - POSTGRES_PASSWORD=rocklee
    volumes:
      - reddit:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  reddit:
