version: "3.8"
services:
  postgres:
    container_name: reddit-db
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=rocklee
      - POSTGRES_PASSWORD=rocklee
    volumes:
      - reddit:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    container_name: redis-cache
    image: redis:6.0.6
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - reddit-cache:/data
    ports:
      - "6379:6379"

volumes:
  reddit:
  reddit-cache:
