version: '3.8'
services:
  postgres:
    container_name: 'reddit'
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=rocklee
      - POSTGRES_PASSWORD=rocklee
    volumes:
      - reddit:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  reddit:
